### ISSUE TITLE
Compiler error integrating from CocoaPods since version 1.16.0

### ISSUE THREAD

**Issue by arivas87** [signalapp/libsignal#594] opened 2024-10-31 08:13 UTC
```
ld: warning: Could not find or use auto-linked library 'signal_ffi': library 'signal_ffi' not found
Undefined symbols for architecture arm64:
  "LibSignalClient.NativeHandleOwner.__allocating_init(borrowing: Swift.OpaquePointer?) -> LibSignalClient.NativeHandleOwner", referenced from:
      full type metadata for LibSignalClient.Aes256Ctr32 in Aes256Ctr.o
      full type metadata for LibSignalClient.Aes256GcmEncryption in Aes256Gcm.o
      full type metadata for LibSignalClient.Aes256GcmDecryption in Aes256Gcm.o
      full type metadata for LibSignalClient.Aes256GcmSiv in Aes256GcmSiv.o
      full type metadata for LibSignalClient.Cds2Client in Cds2.o
      full type metadata for LibSignalClient.ChatListenerBridge.(AckHandleOwner in _7880CDAD24B1514BE930FD806DBED1E8) in ChatListener.o
      full type metadata for LibSignalClient.AuthenticatedChatService in ChatService.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jrose-signal** [comment] 2024-10-31 16:39
Hm, those are missing *Swift* symbols, in addition to the missing Rust library. \*attempts psychic debugging\* Is it possible you only have a build for the x86_64 simulator, but are now running on an arm64 Mac?

Other than that, I'll have to try it out later, none of the 1.16.0 release notes suggest a change that would cause this problem.

**Comment by jrose-signal** [comment] 2024-10-31 19:43
Doing some local testing, it also seems like 1.16 turns on "Build Library for Distribution" for dependencies, which is (a) not a valid thing for them to be doing, and (b) not supported by libsignal. I don't know if that's the cause of these errors (I got a compilation error before even getting to linking), but it's something to be aware of.

**Comment by jrose-signal** [comment] 2024-10-31 19:50
Looks like they're reverting that, so maybe there'll be a 1.16 update soon to get past *that* issue. Then we'll see if there's another one for you. https://github.com/CocoaPods/Xcodeproj/pull/992

**Comment by arivas87** [comment] 2024-11-04 10:16
Sure! It seems to work with the latest CocoaPods release. Due to the end of active support, it would be great to start thinking about a migration to SwiftPM.

**Comment by jrose-signal** [comment] 2024-11-04 17:53
Only when Signal-iOS does, and I think that's a ways off, but I'll let the iOS team know. For now, closing this, glad it works!

**Closed by jrose-signal** 2024-11-04 17:53 UTC
